# Generated by Django 4.2.7 on 2023-11-28 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variacao',
            new_name='Variacoes',
        ),
    ]
